services:
  django:
    image: pets-search-service-backend
    container_name: pets-search-service-backend
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file: .environment
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    networks:
      - pets-search-service-network

  postgres-main:
    image: postgis/postgis:16-3.4-alpine
    container_name: pets-search-service-postgres-main
    ports:
      - "5432:5432"
    volumes:
      - ./storage/postgres-main:/var/lib/postgresql/data
    env_file: .environment
    networks:
      - pets-search-service-network

  minio:
    image: minio/minio
    container_name: pets-search-service-minio
    command: server --console-address ":9001" /data/
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file: .environment
    volumes:
      - ./storage/minio:/data
    networks:
      - pets-search-service-network

  telegram-bot:
    container_name: pets-search-service-telegram-bot
    build:
      context: .
      dockerfile: telegram/Dockerfile
    env_file: .environment
    depends_on:
      - django
    networks:
      - pets-search-service-network


networks:
  pets-search-service-network:
    name: pets-search-service-network
    driver: bridge
